export enum EnglishLore {
  // ─── Players ───────────────────────────────────────────────────────────────

  Player_Kazuma = 'Kazuma Satou is a 17-year-old Japanese shut-in who died an utterly pathetic death — suffering cardiac arrest while convinced he was saving a classmate from a speeding truck, when in reality it was just a slow-moving tractor. Transported to a fantasy world, he picked the Adventurer class, which lets him learn skills from every other class at the cost of no specialization. His freakishly high Luck stat and sharp practical intelligence offset his otherwise mediocre stats. Pragmatic, scheming, and morally flexible, he dreams of a peaceful life but is perpetually dragged into disasters by his chaotic party — and ultimately always takes responsibility for cleaning up the mess.',

  Player_Aqua = 'Aqua is the Goddess of Water and patron deity of the Axis Cult, who once guided the souls of deceased Japanese people to the afterlife — until Kazuma dragged her into the parallel world as petty revenge for her mockery. Despite her near-maxed divine stats in strength, magic, and vitality, her catastrophically low Intelligence and Luck make her reliably useless in practice. She is arrogant, childish, a heavy drinker, and prone to bursting into tears. She wastes skill points on Party Tricks instead of combat abilities. That said, her sacred magic is absolutely devastating against demons and undead, she can purify water, resurrect allies, and even rebuild a wall destroyed by Explosion Magic in a single day — when she deigns to try.',

  Player_Megumin = 'Megumin is an arch-wizard of the Crimson Demon Clan, a race of genetically engineered humans with exceptional magical affinity and an incurable flair for dramatic chūnibyō behavior. She spent all 50 of her skill points on Explosion magic instead of more practical advanced spells, and absolutely refuses to change. Her single daily Explosion is powerful enough to devastate any target, but completely drains her mana and leaves her unable to move until the next day. Theatrical, eccentric, and secretly the most intelligent member of the party, she gradually falls in love with Kazuma despite — or perhaps because of — everything.',

  Player_Darkness = "Lalatina Ford Dustiness, known as 'Darkness', is a noble crusader of the prestigious Dustiness house, nicknamed the Shield of the Kingdom. She inherited monstrous physical resistance from her father and magic resistance from her mother. She almost never lands a hit on enemies — not out of incompetence, but because she intentionally keeps her accuracy low so she can serve as a living shield while her overwhelming Strength stat would end fights too quickly otherwise. Her deep-seated masochism, barely concealed beneath a stoic paladin façade and devotion to the goddess Eris, is the true engine of her courage. She later falls in love with Kazuma after he saves her from an arranged marriage.",

  // ─── Demon King's Generals ────────────────────────────────────────────────

  Creature_Beldia = "Beldia is a Dullahan, an undead knight created from the resentment of an honorable warrior who was unjustly executed, and one of the Demon King's Generals. His severed head floats freely beside his armored body. He was dispatched to Axel to investigate a mysterious light and came into conflict with Kazuma's party after Megumin used his castle as explosion-practice target. Despite his fearsome Herald Death sword and lethal curse ability, he retains the chivalric code of his former life. In private, he is a notorious pervert who used to harass Wiz at the Demon King's castle. His weakness to water led to a humiliating defeat at the hands of Aqua's sacred magic.",

  Creature_HansSlime = "Hans is a Deadly Poison Slime and one of the Demon King's most dangerous and highest-bounty Generals. He usually presents as a tan-skinned human, taking the appearance of those he has devoured. His true form is a colossal mass of translucent purple toxic substance — a single touch means instant death, and anyone he swallows cannot be resurrected. He was sent to Alcanretia to corrupt its hot springs and cripple the Axis Cult's finances. Without remorse, he killed the elderly springs keeper, inadvertently breaking Wiz's neutrality pact. He harbors a visceral, almost traumatic hatred of anything clean — soap, holy water, and Axis Cult members send him into a frenzy.",

  Creature_Sylvia = "Sylvia is a Chimera and one of the Demon King's Generals, renowned for the highest magical resistance among all the Generals. Capable of absorbing living creatures and magical items to incorporate their abilities, she was sent to annihilate the Crimson Demon Village and obtain the sealed weapon known as the Mage-Killer. Charismatic and observant, she saw through Kazuma's real identity when Mitsurugi was busy boasting. Possessing both male and female anatomy as a chimera, she yearned desperately for love. Her defeat required Megumin's Explosion, Kazuma allowing himself to be absorbed to sabotage her anti-magic barrier from inside, and a combined Explosion from Megumin and Yunyun.",

  Creature_Vanir = "Vanir is an Archdemon, a Duke of Hell, and former Demon King's General who now works as a salesman at Wiz's magic shop in Axel. Wearing his signature white mask, he is the 'Devil of Foresight': he can read anyone's soul and predict their every movement and action — except for those more powerful than him, such as other Generals, gods, or Kazuma, whose natural cunning resists his readings. He literally feeds on negative emotions — distress, shame, despair — as if they were fine cuisine, and particularly enjoys being insulted. Ironically refined, he honors contracts to the letter without ever lying. He purchased all of Kazuma's intellectual property rights, recognizing his business genius before Kazuma did. His mutual hatred with Aqua — who keeps accidentally obliterating him with her sacred magic — is a recurring fixture of life in Axel.",

  // ─── Generic Creatures ────────────────────────────────────────────────────

  Creature_AliveTree = "The Alive Tree is a plant creature animated by an ancient and malevolent magic, capable of striking with its branches like whips. It is found in the cursed forests bordering the Demon King's territories. Its natural resistance to ordinary blades makes it a formidable opponent for poorly equipped adventurers. Although it has no true intelligence, its predatory instinct makes it a persistent threat to anyone who wanders into its territory.",

  Creature_AngryShaman = 'The Angry Shaman is a tribal sorcerer in a perpetual state of rage, wielding cursing rituals and summoning rites drawn from obscure ancestral traditions. He typically accompanies monster groups as a spiritual leader, amplifying their aggression through his incantations. His choleric temperament drives him to attack without thinking the moment he perceives a threat. Experienced adventurers prioritize eliminating him to disorganize enemy ranks.',

  Creature_Austrich = 'This Plains Troll is a massive and dim-witted creature whose raw strength more than compensates for its total lack of strategy. It lives alone or in small territorial groups and attacks anything that enters its perimeter. Its thick hide grants natural resistance to ordinary blows, and its slow regeneration lets it endure extended fights. Novice adventurers have learned the hard way that it is better to circle around it than to confront it head-on.',

  Creature_DarkBat = 'The Dark Bat is a nocturnal creature infused with demonic energy that sharpens its claws and enhances its natural echolocation. It hunts in packs in caverns and dark ruins, harassing its prey with unsettling agility. Its small size makes it hard to target, but its limited health points leave it vulnerable to area attacks. Adventurers ill-equipped for fights in darkness often learn this lesson the painful way.',

  Creature_DarkBear = "The Dark Bear is an ordinary bear whose body has been altered by prolonged exposure to the Demon King's energy, granting it multiplied aggression and strength. It prowls the forested zones near cursed territories, attacking anything that crosses its path. Despite its limited intelligence, its predator instinct makes it a serious threat even for mid-level adventurers. Its dark fur partially absorbs light-based spells.",

  Creature_DarkRat = 'The Dark Rat is a mutant rodent infested with demonic energy, far more dangerous than its appearance suggests. It lives in underground colonies beneath cities and dungeons, swarming in darkness waiting for isolated prey. Its bite can transmit debilitating infections that complicate magical healing. Individually weak, it becomes a real threat when attacking in groups.',

  Creature_DarkWolf = 'The Dark Wolf is a predator of the corrupted plains and forests, whose dark coat absorbs light and makes it difficult to spot at night. Intelligent for a monster of its rank, it coordinates pack attacks with formidable efficiency. Its speed and demonically-charged fangs allow it to pierce certain light armors. Shepherds in the Axel region fear it more than any other monster in the area.',

  Creature_Destroyer = "The Destroyer is a gigantic automated siege fortress created by the Demon King, walking on mechanical legs and spreading terror across several regions of the kingdom. Its passage leaves razed villages and destroyed roads in its wake. Its long-range attacks and colossal armor make it nearly impossible to attack through conventional means. Kazuma's party could only defeat it by teleporting its energy core directly into Lord Alderp's mansion — which promptly earned Kazuma an arrest warrant for treason.",

  Creature_Dragon = 'The Dragon is one of the most feared creatures in the world, whose mere presence is enough to empty a town of adventurers. Its scales resist most weapons, and its fire breath can reduce a battalion to ash in seconds. Some dragons possess near-human intelligence and occasionally negotiate with mortals, while others live only for destruction. Engaging a dragon without thorough preparation is outright suicide.',

  Creature_GeneralWinter = "General Winter is a Demon King's General who commands the magic of absolute cold, capable of freezing an entire river in moments. A methodical strategist, he prefers to exhaust enemies with blizzards and waves of icy creatures rather than exposing himself to direct combat. His very presence drastically lowers ambient temperature, making battles grueling even for the best-equipped warriors. His one weakness is a certain tactical rigidity when faced with completely unpredictable approaches.",

  Creature_Ghoul = 'The Ghoul is a hungry undead animated by an insatiable hunger for living flesh, its decomposing body radiating an aura of fear. It prowls near cemeteries and ruins, attacking isolated travelers with bestial ferocity. Its claws and teeth can transmit an infection that slows magical healing if not treated quickly. Though easily defeated by sacred magic, it remains a serious threat in numbers.',

  Creature_GiantEarthworm = 'The Giant Earthworm is an oversized subterranean creature that bursts from the ground to swallow its prey whole. It lives in plains and cultivated fields, causing immense damage to the agricultural infrastructure of the regions it inhabits. Its slimy skin deflects a portion of slashing blows, making swords less effective than blunt weapons or magic. Adventurer guilds rank exterminating these creatures among their most lucrative contracts.',

  Creature_GiantOctopus = "The Giant Octopus is a deep-sea monster whose tentacles can extend several meters to seize and crush its victims. It sometimes ventures into coastal zones or travels up major rivers in search of food. Its magical ink can temporarily blind opponents and disrupt detection spells. Fishermen in the region consider it the most dangerous scourge in the kingdom's waters.",

  Creature_Golem = 'The Golem is a magical construct animated by an energy crystal embedded in its chest, created to guard ancient locations or treasures. Insensible to pain and emotion, it executes its guard duty with absolute mechanical persistence. Its stone fists can shatter even the sturdiest shields, but its slowness leaves it vulnerable to agile combatants. Destroying the crystal at its core is the only reliable way to stop it for good.',

  Creature_GolemQueen = 'The Golem Queen is a colossal and evolved version of the ordinary golem, endowed with a primitive form of intelligence that lets it coordinate other golems. It was created as the supreme guardian of an ancient site of critical importance to the Demon King. Its fists generate shockwaves on impact, and it can partially regenerate its stone casing during combat. Defeating it requires simultaneously neutralizing several energy nodes distributed across its body.',

  Creature_Hydra = 'The Hydra is a multi-headed serpent whose heads can each attack independently, multiplying simultaneous attack angles. Any severed head grows back within hours if the wound is not immediately cauterized by fire or magic. It lives in swamps and humid zones, lurking underwater in wait for careless prey. Experienced adventurers know to coordinate their strikes carefully to avoid accidentally creating more heads than they destroy.',

  Creature_Kamachi = "Kamachi Kaiga is an elite warrior in service of the Demon King's forces, renowned for a mastery of edged weapons that challenges even the most seasoned adventurers. Disciplined and methodical, he studies his opponents before striking, searching for the perfect gap in their defense. His warrior's code of honor sets him apart from ordinary henchmen — he refuses to attack from behind or to target the wounded. This strict ethic is sometimes exploited by less scrupulous opponents to gain the upper hand.",

  Creature_KingTroll = 'The King Troll is the undisputed leader of a troll tribe, imposing his dominance through raw strength and a frame twice the size of his peers. He possesses rudimentary intelligence that allows him to lead organized raids on villages and merchant caravans. His regeneration is significantly faster than that of ordinary trolls, making prolonged fights favor him. Adventurer guilds offer a substantial bounty for any proof of his defeat.',

  Creature_Knight = 'The Cursed Knight is a once-honorable warrior whose soul was corrupted by a demonic curse, condemning him to serve the forces of darkness for eternity. He retains his sharp combat reflexes and solid armor, but any personal will has long since vanished. Some say that deep within his empty eyes, fragments of his former consciousness still flicker, begging to be freed. Only powerful sacred magic can break the curse and grant him peace.',

  Creature_LoveBunny = "The Love Bunny is a cute but deceptive creature whose harmless rabbit appearance conceals an aggressive and possessive nature. It emits magical pheromones that irresistibly lure careless adventurers into its territory. Despite its weak attack power, it can bite with surprising ferocity when cornered. Axel's novice adventurers have often been unpleasantly surprised by underestimating it due to its adorable appearance.",

  Creature_MaidBot = 'The Maid Bot is a combat automaton created by the Demon King under the guise of a helpful domestic servant, concealing integrated weapons behind an inoffensive façade. Programmed to infiltrate noble residences and adventurer bases, it eliminates targets with clinical precision. Its outer shell perfectly mimics human expressions, making detection particularly difficult before it is too late. Intelligence guilds have implemented identification protocols to spot these mechanical infiltrators.',

  Creature_MedusaMan = 'The Medusa Man is a half-human, half-medusa creature capable of petrifying opponents with a prolonged direct gaze. It lives in rocky terrain and caverns, surrounded by stone statues that are in reality its past victims. Its hybrid biology grants poison resistance and surprising agility despite its unsightly appearance. Adventurers fight it systematically with eyes averted or shielded by a mirror, making combat particularly treacherous.',

  Creature_Milim = 'Milim Nava is a Demon Lord of cataclysmic power, considered one of the strongest beings in her world of origin. Childlike in behavior, she swings between petty tantrums and bursts of power capable of leveling entire mountain ranges. Her friendship is as precious as it is dangerous: crossing her can trigger regional-scale catastrophes. Her presence in this world as an enemy is a clear signal that the situation has completely spiraled out of control.',

  Creature_Minotaur = 'The Minotaur is a colossal half-man, half-bull whose physical strength exceeds most monsters of its rank. It lives in labyrinths and deep dungeons, jealously guarding the heart of its territory against any intruder. Its devastating charges can tear through entire shield formations, and its horns strike with the force of a siege ram. Only great agility or a ranged attack can keep a fighter off its direct line of charge.',

  Creature_PigWoman = 'The Pig Woman is a porcine humanoid creature often encountered in shady towns and markets, running dubious businesses with animal cunning. Minimally dangerous in open combat, she compensates with traps, calls for the guard, or hidden accomplices in back alleys. Her greedy nature makes her corruptible, but trying to bribe her without paying the right price can easily backfire. She is less a physical threat than a social and economic obstacle for adventurers.',

  Creature_Quomodo = 'The Komodo is a gigantic predatory lizard whose jaw can crush ordinary metal armor and whose saliva carries paralyzing bacteria. It hunts alone in arid plains and rocky zones, lying in ambush with remarkable patience before charging its prey. Its scaly hide offers natural resistance to edged weapons, forcing opponents to aim for the joints or use blunt weaponry. Healers dread its bites, as the resulting infections resist ordinary potions.',

  Creature_Ruijerd = 'Ruijerd Superdia is a Superd, a member of an elite race of warriors who carry a crystalline spear and a mark on their forehead, universally feared and wrongly despised in their world of origin. Stoic and absolutely righteous, he has imposed upon himself a strict code of honor forbidding him from lying or abandoning those he has decided to protect. His reputation as a bloodthirsty monster is a historical injustice he bears without complaint. His appearance as an enemy is a sign of outside manipulation — his deeply loyal nature is fundamentally incompatible with unprovoked aggression.',

  Creature_Samurai = "The Samurai is a warrior from eastern lands in service of the Demon King's forces, mastering a quick and precise blade style unknown in western kingdoms. His martial discipline grants him an attack speed superior to most local knights, unsettling fighters accustomed to classical styles. He follows a personal code of honor that sometimes conflicts with the orders he receives. Adventurers who survived a duel with him report that his technique is as elegant as it is merciless.",

  Creature_SharkMan = 'The Shark Man is an aquatic humanoid with shark-like features, capable of fighting as effectively on land as in water thanks to his powerful legs and adapted gills. His jaws are a formidable natural weapon that can crush wooden shields in seconds. He lives in organized packs in coastal zones, launching raids on fishing villages with surprising coordination. His battle rage increases proportionally with the damage he takes, making him an even more dangerous foe when wounded.',

  Creature_Slime = 'The Slime is a gelatinous mass whose simple form conceals near-total resistance to physical attacks and the ability to slowly dissolve everything it engulfs. It is found in dungeons and humid zones, luring careless adventurers through its harmless appearance. Its primary weakness lies in fire or intense cold, which alter its internal structure and break its cohesion. Rare and vastly more dangerous variants exist — such as the Deadly Poison Slime, whose most terrifying example is Hans, a General of the Demon King.',

  Creature_Squall = 'Squall is a wind elemental spirit with its own consciousness, capable of generating razor-sharp gusts that can lacerate light armor. It manifests during storms or in zones of intense magical activity, drawn to concentrations of elemental energy. Capricious and unpredictable, it shifts targets according to its moods without any apparent tactical logic. Mages specializing in earth magic struggle to affect it, but lightning spells neutralize it quickly.',

  Creature_Toad = 'The Toad is a giant amphibian whose sticky tongue can snatch prey from several meters away in a flash. It lives in the swamps and humid zones around Axel, perfectly camouflaged in the vegetation thanks to its mottled skin. Its saliva is mildly paralyzing on contact, slowing the reflexes of adventurers who do not take precautions against it. Local guilds regularly issue extermination contracts as its presence threatens the trade routes bordering the marshes.',

  Creature_Troll = 'The Troll is a brutal and dim-witted creature whose phenomenal strength more than compensates for its complete absence of tactical finesse. It lives in groups in forested and mountainous zones, attacking anything that enters its perimeter with boundless energy. Its slow regeneration lets it recover from light wounds between fights, discouraging enemies who fail to finish their targets quickly. Fire remains the most effective method for permanently neutralizing its regenerative capabilities.',

  Creature_UglySpirit = "The Ugly Spirit is a spectral entity born from the most corrupted and spiteful of souls, whose repulsive appearance reflects the inner darkness of what it once was. It haunts ruins and sites of ancient tragedy, draining the life energy of living beings who wander too close. Its attacks pass through physical armor, rendering conventional defenses entirely useless against it. Aqua's sacred magic is particularly devastating against this creature — one of the rare situations where her divine powers prove genuinely useful.",

  Creature_Wizard = "The Wizard is a corrupted mage who sold his services to the Demon King's forces in exchange for enhanced magical power, at the cost of his moral freedom. He commands a variety of offensive spells ranging from fire projectiles to debilitating curses, adapting his arsenal to the situation. His intelligence, superior to that of ordinary monsters, makes him capable of effective counter-strategies if given time to act. Support classes target him first, since allowing a wizard to act freely can turn the tide of an entire battle.",
}
