name = "konosuba-rpg"
type = "typescript"
main = "src/index.ts"
compatibility_date = "2026-03-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env]
workers_dev = true

[vars]
DISCORD_TOKEN = "your-discord-token-here"
PUBLIC_KEY = "8d61a524ccac360a3fd47de09c8df98487e7bec67884e4004feee5b1eb81062d"
APP_ID = "1228368274488819792"

[triggers]
branch = "main"